use_frameworks!

target 'FMCardCell_Example' do
  pod 'FMCardCell', :path => '../'

  target 'FMCardCell_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
